# -*- coding: utf-8 -*-
"""personal_intro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15baQCHhc2SEb8FkYZtgKzw6x8LIGMkNM
"""

name = input("What is your name? ")
age = input("How old are you? ")
nationality = input("What is your nationality? ")
hobby = input("What is your favorite hobby? ")

print("\n===================================")
print("      PERSONAL INTRODUCTION")
print("===================================")

print(f"Name        : {name}")
print(f"Age         : {age}")
print(f"Nationality : {nationality}")
print(f"Hobby       : {hobby}")

print("\n🎉 Welcome", name, "🎉")
print(f"You are {age} years old.")
print(f"You are from {nationality}.")
print(f"Your favorite hobby is {hobby}.")
print("Thank you for sharing your information!")